name: CI/CD Pipeline For Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: root                      # Run as root since repo is in /var/www
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          debug: true
          script: |
            cd /var/www/helloapp/python-github-actions-demo || git clone https://github.com/ABYUF/python-github-actions-demo.git /var/www/helloapp/python-github-actions-demo
            cd /var/www/helloapp/python-github-actions-demo
            git pull origin main

            # Create virtual environment if it doesn't exist
            if [ ! -d ~/myvenv ]; then
              python3 -m venv ~/myvenv
            fi

            source ~/myvenv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Restart systemd service
            systemctl restart helloapp.service
            echo "===== Last 20 lines of helloapp.service logs ====="
            journalctl -u helloapp.service -n 20 --no-pager
